Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,5 +1,7 @@
 name: Automatisation des tests
 on: push
+jobs:name: Automatisation des tests et déploiement
+on: push
 jobs:
   Compilation:
     runs-on: ubuntu-latest
@@ -14,3 +16,95 @@ jobs:
           cmake ..
           make
           make test
+ 
+  Test_Add:
+    runs-on: ubuntu-latest
+    needs: Compilation
+    steps:
+      - name: Test fonction add
+        run: |
+          last_directory=$(basename ${{ runner.workspace }})
+          git clone https://github.com/${{ github.repository }}.git
+          cd ./$last_directory
+          mkdir build
+          cd build
+          cmake ..
+          make
+          ./src/calculator add 10 5
+          
+  Test_div:
+    runs-on: ubuntu-latest
+    needs: Compilation
+    steps:
+      - name: Test fonction div
+        run: |
+          last_directory=$(basename ${{ runner.workspace }})
+          git clone https://github.com/${{ github.repository }}.git
+          cd ./$last_directory
+          mkdir build
+          cd build
+          cmake ..
+          make
+          ./src/calculator div 10 5
+             
+  Test_mul:
+    runs-on: ubuntu-latest
+    needs: Compilation
+    steps:
+      - name: Test fonction mul
+        run: |
+          last_directory=$(basename ${{ runner.workspace }})
+          git clone https://github.com/${{ github.repository }}.git
+          cd ./$last_directory
+          mkdir build
+          cd build
+          cmake ..
+          make
+          ./src/calculator mul 10 5
+  
+  Test_sub:
+    runs-on: ubuntu-latest
+    needs: Compilation
+    steps:
+      - name: Test fonction sub
+        run: |
+          last_directory=$(basename ${{ runner.workspace }})
+          git clone https://github.com/${{ github.repository }}.git
+          cd ./$last_directory
+          mkdir build
+          cd build
+          cmake ..
+          make
+          ./src/calculator sub 10 5
+
+  Test_squa:
+    runs-on: ubuntu-latest
+    needs: Compilation
+    steps:
+      - name: Test fonction squa
+        run: |
+          last_directory=$(basename ${{ runner.workspace }})
+          git clone https://github.com/${{ github.repository }}.git
+          cd ./$last_directory
+          mkdir build
+          cd build
+          cmake ..
+          make
+          ./src/calculator squa 5
+
+  Deploy:
+    runs-on: ubuntu-latest
+    needs: [Test_Add, Test_div, Test_mul, Test_sub, Test_squa]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+  
+      - name: Deploy to server
+        env:
+          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
+          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
+          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
+        run: |
+          echo "Starting deployment"
+          scp -r build/* $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH || echo "Deploy failed"
+          echo "Deployment complete"
